README.md

fix link to website

---

notebooks/Playground.ipynb

Sorry for that.
Note that this notebook cell never actually worked for me, even before #40. So I'm only updating that code, but can't figure out to fully make it work, it behaves weirdly.

Oops, forgot adapting notebook to #40, fixes #44.

---

pommerman/cli/train_with_tensorforce.py

enable `pom_tf_battle --render='' ...` to be more like `pom_battle --render='' ...`

Tensorforce: fix --render='' option

---

pommerman/agents/simple_agent.py
pommerman/envs/utility.py

About a 3x improvement in SimpleAgent speed:
•	Use PriorityQueue in djikstra
•	Call djikstra less frequently
•	Reduce the depth at which djikstra is called.

Simple Agent Speedups

---

pommerman/README.md

https://github.com/MultiAgentLearning/playground/blob/master/pommerman/constants.py#L78

Fix navigation in README

---

CONTRIBUTING.md
README.md
docs/CLI.md

This deals with the issue #67.
Are there any other things we need to add to the contributing guide?

Documentation update

---

setup.py

setup script to include game resources

---

docs/README.md

Do you think this is enough? Anything else that needs to be added or changed?

Added section on how to submit an agent

---

pommerman/cli/run_battle.py
pommerman/envs/v0.py
pommerman/utility.py
requirements.txt

This deals with #72. 
~~I removed the JSON save from the render so you can save game state without rendering the game.~~ also added a util to merge all of the final game states into one file. 
~~There are also some changes in the `run_battle` to support the removal of saving JSON files from the render method.~~

added support for single game state file

---

pommerman/forward_model.py

Undo bomb kicks if the agent's move needs to be reversed.
( Failed kick by another agent causes new collision)
Bounce moving bombs (not directly involved in kicks) back to original position if an unrelated failed kick (or the consequences thereof) cause a late collision with an agent.
Tested manually with an ugly, tiny (not automated) test framework around the step function.
( Agents, Bombs position/direction/actions specified manually, board dump verified before/after )

Fix step function to not bounce back agents after successful kick.

---

README.md

Added fix for the two links that were broken on master/README.md with the new links in Issue125Branch/README.md
The additional fix was the code of conduct link, which I didn't know was broken when I opened the issue

Issue125 branch

---

notebooks/Playground.ipynb

PR for this [issue](https://github.com/MultiAgentLearning/playground/issues/128)
Tested running the whole notebook locally.

replace `ffa_v0_env` by `ffa_v0_fast_env` in notebook

---

pommerman/agents/simple_agent.py

Issue #138

---

scripts/build_sample_docker_agent
scripts/run_sample_docker_agent

Should be helpful to those not familiar with Docker.

Add basic scripts for running example Docker agent

---

.travis.yml

http://pylint.pycqa.org/en/latest/user_guide/run.html#parallel-execution

The magic of parallel-execution (pylint)

---

pommerman/__init__.py
pommerman/network/server/__init__.py
pommerman/network/server/network.py

This bug was caused due to a last minute change.

Fix major bug in Server

---

pommerman/__init__.py
pommerman/network/client/network.py
pommerman/network/server/__init__.py
pommerman/network/server/network.py

Bugfix: Fix critical issues with the Server regarding WebSockets

---

pommerman/envs/v1.py

My test framework is currently broken and this is 100% untested.
( I should be able to test before the end of the month - but happy if someone can beat me to it )

Remove flames on collapsing wall. (#204)

---

docs/getting_started.md

Added how to use neurips 2018 docker agents

Added how to use neurips 2018 docker agents

---

docs/README.md
docs/getting_started.md
env.yml

I forgot to update docs for installation in the last merged pull request.
And in this PR, `env.yml` is updated to support Python 3.7.3.

Add docs for creating a Conda environment and update `env.yml`

---

pommerman/network/client/__init__.py
pommerman/network/server/__init__.py

The init_agent method of an agent is now called.

Call init_agent

---

pommerman/agents/tensorforce_agent.py

fix wrong action type declared in tf agent

---

pommerman/runner/docker_agent_runner.py

add missing obs transform 'bomb_moving_direction' in docker runner
