- games/a/pommerman/envs/v0.py
- games/train_with_tensorforce.py
This fixes a bug where a dead player creates an invisible wall.
The code was trying to set the agent's `next_position` to `None`, so that it wouldn't register in the position conflict checking, but instead it was _appending_ `None` to `next_positions`.  This caused dead agents to always create position conflicts at their death spot.
It was a one-line fix.
> fix dead player position conflict bug

- games/a/pommerman/characters.py
- games/a/pommerman/envs/utility.py
- games/a/pommerman/envs/v0.py
- games/run_battle.py
Serialize game state into human readable JSON.
The save is gametype/agent agnostic, to be able to reload a board with a different setup.
**Record game example:**
python run_battle.py --agents=test::a.pommerman.agents.SimpleAgent,test::a.pommerman.agents.SimpleAgent,test::a.pommerman.agents.SimpleAgent,test::a.pommerman.agents.SimpleAgent --config=ffa_v0 --record_json_dir=./jsons
**Replay game from step 50 example:**
python run_battle.py --agents=test::a.pommerman.agents.SimpleAgent,test::a.pommerman.agents.SimpleAgent,test::a.pommerman.agents.SimpleAgent,test::a.pommerman.agents.SimpleAgent --config=ffa_v0 --game_state_file=./jsons/50.json
> Serialize game state into json

- GettingStarted.md
- pommerman/__init__.py
- pommerman/agents/base_agent.py
- pommerman/agents/player_agent.py
- pommerman/cli/train_with_tensorforce.py
- pommerman/envs/v0.py
- pommerman/utility.py
First commit slightly refactors the code, moving input-control code from `utility.py` to `player_agent`. I think that's more proper anyways.
The second commit makes use of that change in order to allow same-screen multiplayer mode :smile: Just have two agents as `player::arrows,player::wasd` and give it a try! Also updated the `GettingStarted.md` accordingly.
Supersedes #38, close #38.
> Multiplayer mode!

- pommerman/__init__.py
- pommerman/cli/run_battle.py
What this is still missing, is the parsing of docker env variables to be
passed to the agent. It's missing, because I have no clue about that and
so wouldn't even know how to test my attempt at fixing it :smile:
(The problem is the change in `make` interface but missing adaptation of `run_battle.py` as I mention [here](https://github.com/MultiAgentLearning/playground/pull/40#issuecomment-376984803))
> Partially fix run_battle.py, which broke in #40.

- pommerman/envs/utility.py
"Fix" in quotes because I still think that's not a real pause functionality :smile: 
I looked into turning it into a real pause, that can be unpaused. That's actually not trivial in the current codebase. The more I think about it, the less I believe this should be an actual action that an agent makes!
1. You don't really want the agent to learn about pause/unpause, do you? So it's not part of the agent's formal action space, but [currently it kinda is](https://github.com/MultiAgentLearning/playground/blob/master/pommerman/envs/v0.py#L60).
2. Since the pause can only be triggered by a human player's key-press, I believe you only want to use this pause from humans, right? In that case, pausing/unpausing should be part of the human user-interface, not of the agent or forward model. So I …
> "Fix" the pause code (missing import).

- pommerman/agents/player_agent.py
The comment on top should describe both the problem of the current approach, as well as the new proposed approach, so I won't repeat it here. Code is extensively commented as otherwise it looks needlessly over-engineered, but it isn't.
The magic numbers used (`0.2` and `0.1`) are what I remember using in past games, but could be tweaked. For example, my linux uses `0.66` and `0.025` (check yours using `xset q | grep 'auto repeat delay'`) but I felt it was too delayed for a game.
Getting user input feel "natural" is actually nontrivial (I know from experience) and super-simple code almost never feels right. I know it wasn't a priority for this project, but it felt frustrating play-testing it and losing to `SimpleAgent` because of input issues, not skill. With this patch, I'm still losing …
> Implement more natural human player input.

- docs/CLI.md
- pommerman/cli/run_battle.py
- pommerman/cli/train_with_tensorforce.py
Now the game is not rendered by default and rendering is enabled via adding --render.
> fixing --render argument

- pommerman/agents/simple_agent.py
- pommerman/forward_model.py
- pommerman/utility.py
New agent and bomb movement logic.
Add seconday bomb explosions and restore explode on fire functionality.
Kill agents that walk into fire.
forward_model: some style fixes and comments, plus a change to get_info to fix that it wasn't returning correctly when all living agents died on a single turn.
> New step logic

- examples/simple_ffa_run.py
The global variable in pommerman is called "REGISTRY", instead of "registry", which causes the example to crash.
> Fixed small bug in example_ffa_run

- pommerman/cli/run_battle.py
- pommerman/envs/v0.py
moved the call of the inherited method episode_end to be implicitly called by the environment at the end of an episode.
> moved the episode_end call to be called by the environment

- pommerman/__init__.py
`gym` outputs `?[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.?[0m` on Windows whenever it's imported. This fixes it by lowering the debug level.
> Fix minor debugging warning on Windows

- pommerman/agents/__init__.py
- pommerman/agents/http_agent.py
- pommerman/helpers/__init__.py
Example http agent usage:
pom_battle --agents simple::null,simple::null,http::localhost:8085,simple::null --render
PR is mostly a  copy & paste from docker agent and some fixes for broken agent selection CLI.
Would be nice to use it as a base for the docker agent to avoid duplicated code - but don't really have the time.
> Add http agent and fix agent helper. (#42)

- pommerman/cli/run_battle.py
An example when we want to record a json file for later on replay without using render.
> record the json file for replay when render is off

- pommerman/agents/docker_agent.py
- pommerman/agents/http_agent.py
My understanding is that len(action_space.shape) is zero, so action is
empty. This solution works, but may not be the most beautiful either.
> Choosing IDLE action crashed when agent timeouted.

- docs/environment.md
Correcting the documentation for encoding of rigid and wooden walls in 'board' array which would solve issue #196
> Updating the encoding in documentation

- pommerman/agents/__init__.py
- pommerman/agents/player_agent_blocking.py
- pommerman/helpers/__init__.py
- requirements.txt
Same as https://github.com/MultiAgentLearning/playground/pull/206/ but:
- ran yapf on pommerman/agents/player_agent_blocking.py
- squashed to 1 commit
> Fixes 115: Added blocking keyboard player (squashed commits)

- pommerman/graphics.py
imresize was deprecated in scipy 1.0 and removed in scipy 1.3. Failed to run therefore by default on Google Colab
Sorry for opening another pull request. I deleted my other forked repo and that kind of broke everything on github.
> replace scipy resize by PIL

- docs/environment.md
- pommerman/characters.py
- pommerman/envs/v0.py
- pommerman/forward_model.py
As requested in issue #202 adds further array to observation of an agent. `flame_life` ticks down like the bombs except it starts at 3.
EDIT: also added bomb movement direction in as further map of ints where bomb movement is int in action space
EDIT 2: when squashing commits `make_flame_map` function got copied twice. The second force push removed that error.
EDIT 3: the third force push were two spelling errors I found in the documentation. My bad!
> Issue #202 add flame life + bomb movement

- pommerman/forward_model.py
Previously this was only done if the state was partially observable. Therefore the fully-observed version led to in-place modifications of the observations when the state of the environment changed (board in state and board in next_state are would be the same)
> Bugfix: Board is always copied when returned as an observation

- pommerman/runner/docker_agent_runner.py
Following #249, I oversaw another missing obs conversion in the docker runner for 'flame_life'. Cross-checking with the forward model `get_observations` there are no other observations that need to be handled.
Thanks for @cinjon for handling issues / PR's so quickly.
> add missing obs transform 'flame_life' in docker runner

- pommerman/envs/v2.py
Solves #253 
Adds import of 'json' module  + missing 'json_encoder' declaration and converts enum to string (and back) for json dump/load.
> fix get_json_info and set_json_info functions in v2 env
